# Generated by Django 2.1.2 on 2018-10-21 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('group_chat_avatar', models.CharField(default='/statics/img/default_avatar_male_180.gif', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msg_type', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('country', models.CharField(default='中国', max_length=30)),
                ('province', models.CharField(default='北京', max_length=30)),
                ('city', models.CharField(default='北京', max_length=30)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女'), (-1, '未知')])),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=18)),
                ('signature', models.TextField()),
                ('avatar', models.CharField(default='/statics/img/default_avatar_male_180.gif', max_length=128)),
                ('status', models.CharField(choices=[('ON', 'online'), ('OFF', 'offline')], default='OFF', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_from_user', to='chat.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_to_user', to='chat.User'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='group_chat_members',
            field=models.ManyToManyField(to='chat.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(to='chat.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='chat.User'),
        ),
    ]
