# Generated by Django 2.1.2 on 2018-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, null=True, upload_to='statics/upload/%y%m%d')),
            ],
        ),
    ]
