# Generated by Django 2.1.2 on 2018-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='statics/upload/%y%m%d')),
            ],
        ),
    ]
