# Generated by Django 2.1.2 on 2018-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OFF', 'hide')], default='OFF', max_length=8),
        ),
    ]
