# Generated by Django 2.1.2 on 2018-10-29 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181026_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/statics/img/default_avatar_male_180.gif', max_length=128, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='北京', max_length=30, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='中国', max_length=30, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(default='北京', max_length=30, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (-1, '未知')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.TextField(verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ON', 'online'), ('OFF', 'hide')], default='OFF', max_length=8, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
