# Generated by Django 2.1.2 on 2018-11-05 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='客服名称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(default='/statics/img/default_avatar_male_180.gif', max_length=128, verbose_name='客服头像')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='客户昵称')),
                ('avatar', models.CharField(default='/statics/img/default_avatar_male_180.gif', max_length=128, verbose_name='客户头像')),
                ('ip', models.CharField(default='0.0.0.0', max_length=64, verbose_name='客户IP')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='对话名称')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='agent.Agent')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='agent.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_id', models.CharField(max_length=255)),
                ('to_id', models.CharField(max_length=255)),
                ('msg_type', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
