# Generated by Django 2.1.2 on 2018-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_statement_dialogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='访客', max_length=100, verbose_name='客户昵称'),
        ),
    ]
